language: node_js
node_js:
  - "10"
dist: trusty
cache: yarn
notifications:
  slack:
    secure: YCqAk/0OY7CAFIvciP5P11n/f0HQX+Or9MdFTd1exGESTcJrYoZi4CKrLE//1LtrG3zX+zJtrskyAhAPMe/X4DtMoQd0dE7CEBk3+KVJJVrsHbUVtnlCjs0pFGyrfWndtvWxWmqO+T2xVPcXo+r/Ks6135BnKeO4yzlUpppDtEixfpgLkXJdMDEAzaknA4TlqkOhY7R7UZkU0mBtCdqg6Qnz3BA+wo9gvZ2LDIrihCIixVAVyvfJLsBq3WiyFx9ev8TsoFm8rZfCDoTtA0JgE+CJKQZihUaIwDuOyjYssCle1RtCeL+r2ejUIX57ExtkyttNFbYJJ81QNNJeyqCoowhfC39dF3u20gMBbWMj/gzh0lN1au83e4yzqSedaLAHVNOmkfkpIgbd+3Wok1rqpgyTggeYxdchJPcOsGNxIqd2TnCdU7Uv4DXELH3l811B2UTvTCvywNw3B1Mw4HwHuxxdidA7kTj1Zkt44HEimxvgc25jMICdmyVTvJ+x12ZKUu5b1dr4nU1pDB8DJxOUDu2uRRw0gF+vFJQHM9eOFqkNT4vOH4siffV72DZ/3HjhhmEKLnuBQR1xFltQp7z/BVUKsyoLzsleqRxaGZ5vRIAtHjj0Gjv9f49Yk8FguOx8ZEEigI0MWxnYLXREMKl3V2sVz6MaSKjgK7LHlV6uhGQ=
